### ISSUE TITLE
App getting close automatically after few seconds with blank screen

### ISSUE THREAD

**Issue by Ammar-Ishfaq** [DakeQQ/Native-LLM-for-Android#1]
Hello, I've compiled the project and run it on Samsung s22 and Android 14 upon launching of app it's just black (or either white screen sometimes).

**Comment by DakeQQ** [comment]
I'm happy to see someone is starting a trial. Following the checklist below may help you solve the problems:
Please follow the chek-list may help you solvong the problems.
1. Manually unzip the so.zip file, which is located in 'app/libs/arm64-v8a'. You will obtain the necessary *.so and *.h files. Place them directly into the arm64-v8a folder, without using any sub-folder paths.
![屏幕截图 2024-03-07 123515](https://github.com/DakeQQ/Native-LLM-for-Android/assets/160212901/805937c4-76b2-4a17-8d63-f0f30d7d5742)
2. Download the model from the provided link and place it directly into the assets folder, without using any sub-folder paths.
3. The peak memory usage reaches approximately 4GB while loading the *.ort model. Please ensure there is sufficient system memory available to proceed with the launch.

Please feel free to ask any other questions if they exist.

**Comment by Ammar-Ishfaq** [comment]
I've followed the instructions (I've attached the SS below 
![image](https://github.com/DakeQQ/Native-LLM-for-Android/assets/54596139/6e42af00-e6fd-4101-b284-b92951c16226)
)
Also, I download the .ort models in the assets directory.
But it's not working on my Samsung s22, I've tried multiple times (relaunching).
Could you please tell me some way like the way I can get this running?

**Comment by DakeQQ** [comment]
Let's give it another try.

1. Turn on the S22's performance mode and close all background apps.
2. Temporarily comment out the model loading code located on line 59 in MainActivity.java, and also avoid using "runOnUiThread()".
![屏幕截图 2024-03-08 180549](https://github.com/DakeQQ/Native-LLM-for-Android/assets/160212901/dab23ea5-ee2c-4345-9202-edb40507f69a)
3. After completing step 2, build and launch the app. If it successfully enters the chat screen, it indicates that the problem occurs during the model loading process.
4. According to the loading code, if there are any issues with the ORT model, it should display a 'load failed' message. However, it crashes directly without reaching the chat screen. This suggests there may be system-related issues on the S22.
5. The problem might be related to insufficient memory or hardware permissions, I suspect. If it's a matter of memory shortage, consider using a smaller LLM model like 'Qwen_v1.5, 0.5B param', which requires around 1.4GB for peak loading and 700MB for chatting.
6. If you're still interested in achieving successful execution, please allow me a few days (possibly by next weekend) to try exporting the 0.5B version to the cloud. Alternatively, you might want to try using a different phone, preferably not from the Samsung series.

**Comment by DakeQQ** [comment]
I have an Android Phone running Android 13, equipped with an 8Gen2 processor, and 12GB RAM, experiencing the same phenomena you encountered. It consistently crashes when creating the .ort model in project.cpp at line 391.

Here's what I've tried:
1. Changed the ONNX *.so library version, but it still crashes.
2. Disabled all the ONNX session options, but it still crashes.
3. Disabled all the CMakeList optimize options, but it still crashes.
4. Changed the NDK version, but it still crashes.
5. Changed the JDK version, but it still crashes.
6. Changed the Gradle version, but it still crashes.
7. Ran another project that uses the same ONNX libraries & Java configuration with a small voice recognition model, and it worked!

- Therefore, I suspect it is being limited by the OS for some reason (possibly due to excessive memory usage by an unknown app). If you're interested, you can try my other projects. Thanks for your trial and feel free to ask any other questions.

**Comment by DakeQQ** [comment]
Strangely, after switching the phone to performance mode, clearing all background apps, and rebooting it, I cleaned and rebuilt the project again. Finally, it worked without any changes!

**Comment by Ammar-Ishfaq** [comment]
Sure, I'll try that and see if it works for me.
